# Generated by Django 5.0.9 on 2025-01-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("species", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.BinaryField(editable=True)),
                ("length", models.IntegerField(default=0, editable=False)),
                ("gc_content", models.FloatField(default=0.0, editable=False)),
                ("annotation", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("sequence", models.TextField()),
                ("length", models.IntegerField(editable=False)),
                ("gc_content", models.FloatField(default=0.0, editable=False)),
                ("annotated", models.BooleanField(default=False)),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeneAtlas.genome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peptide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Peptide", max_length=100)),
                ("sequence", models.TextField()),
                ("length", models.IntegerField(editable=False)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="GeneAtlas.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "gene",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="GeneAtlas.gene",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
