# Generated by Django 5.0.9 on 2025-01-11 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("species", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("header", models.TextField(default=">Genome")),
                ("sequence", models.BinaryField(editable=True)),
                ("length", models.IntegerField(default=0, editable=False)),
                ("gc_content", models.FloatField(default=0.0, editable=False)),
                ("annotation", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("header", models.TextField(default=">Gene")),
                ("sequence", models.TextField()),
                ("length", models.IntegerField(editable=False)),
                ("gc_content", models.FloatField(default=0.0, editable=False)),
                ("annotated", models.BooleanField(default=False)),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeneAtlas.genome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peptide",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="Peptide",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("header", models.TextField(default=">Peptide")),
                ("sequence", models.TextField()),
                ("length", models.IntegerField(editable=False)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="GeneAtlas.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneAnnotation",
            fields=[
                (
                    "gene_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="GeneAtlas.gene",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("annotation", models.TextField(default="No annotation provided.")),
                ("strand", models.IntegerField(default=1)),
                ("gene", models.TextField(default="No gene provided.")),
                ("gene_biotype", models.TextField(default="No gene biotype provided.")),
                (
                    "transcript_biotype",
                    models.TextField(default="No transcript biotype provided."),
                ),
                ("gene_symbol", models.TextField(default="No gene symbol provided.")),
                ("description", models.TextField(default="No description provided.")),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeptideAnnotation",
            fields=[
                (
                    "peptide",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="GeneAtlas.peptide",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("transcript", models.TextField(default="No transcript provided.")),
                (
                    "annotation",
                    models.OneToOneField(
                        default="No annotation provided.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeneAtlas.geneannotation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
